# Generated by Django 4.2.4 on 2023-10-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ManyToManyField(to='diet_models.ingredient'),
        ),
    ]
