# Generated by Django 4.2.4 on 2023-10-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_models', '0002_remove_ingredientquantity_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diet_models.ingredient'),
        ),
    ]
