# Generated by Django 4.2.4 on 2023-09-23 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_models', '0003_alter_mealtime_meal_alter_mealtime_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_models.meal'),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='name',
            field=models.CharField(blank=True, choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], null=True),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='timeofday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_models.timeofday'),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
