# Generated by Django 4.2.4 on 2023-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_models', '0003_remove_ingredientquantity_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtime',
            name='name',
        ),
        migrations.AddField(
            model_name='mealtime',
            name='day',
            field=models.CharField(choices=[('Mon', 'Poniedziałek'), ('Tue', 'Wtorek'), ('Wed', 'Środa'), ('Thu', 'Czwartek'), ('Fri', 'Piątek'), ('Sat', 'Sobota'), ('Sun', 'Niedziela')], default='Mon', max_length=3),
        ),
    ]
