# Generated by Django 4.2.4 on 2023-09-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_models', '0004_alter_mealtime_meal_alter_mealtime_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtime',
            name='user',
        ),
    ]
