# Generated by Django 4.2.4 on 2023-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_models', '0006_mealtime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='name',
            field=models.CharField(blank=True, choices=[('Poniedzialek', 'Poniedzialek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], null=True),
        ),
    ]
